-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgAccuUuqITUcdd0fW
6SbN+/G4pNnPaAGSOn0GnOvmrOigCgYIKoZIzj0DAQehRANCAAQMDTIR2pibNl+b
oBMegB+D5I/10JGiCDWmva7OM3DhBuXQ8XE0w2d+RAXluEXuC5Nffp/jg9V0kgKg
qNgVdQAx
-----END PRIVATE KEY-----